export const sampleCourses = [
  {
    id: "1",
    title: "Quran Memorization (Hifz Program)",
    titleAr: "برنامج حفظ القرآن الكريم",
    description:
      "A comprehensive Hifz program designed to help students memorize the entire Quran with proper Tajweed rules and pronunciation under the guidance of experienced Qaris.",
    category: "Quran",
    level: "beginner",
    duration: "2 years",
    students: 120,
    instructor: {
      id: "i1",
      name: "Sheikh Ahmad Al-Rashid",
      title: "Head of Quran Department",
    },
    schedule: "Daily, 6:00 AM - 8:00 AM",
    price: 0,
    currency: "ETB",
    syllabus: [
      "Introduction to Tajweed rules",
      "Memorization techniques and methods",
      "Daily memorization sessions",
      "Weekly revision classes",
      "Quarterly assessments",
      "Final Hifz completion ceremony",
    ],
    requirements: [
      "Basic Arabic reading ability",
      "Commitment to daily practice",
      "Minimum age: 7 years",
    ],
    featured: true,
    enrollmentOpen: true,
    maxStudents: 150,
    startDate: "2026-03-01",
    endDate: "2028-02-28",
    masjidId: "1",
  },
  {
    id: "2",
    title: "Arabic Language for Beginners",
    titleAr: "اللغة العربية للمبتدئين",
    description:
      "Learn classical Arabic from the basics including reading, writing, grammar, and conversation skills essential for understanding Islamic texts.",
    category: "Language",
    level: "beginner",
    duration: "1 year",
    students: 85,
    instructor: {
      id: "i2",
      name: "Ustadha Maryam Hassan",
      title: "Arabic Language Instructor",
    },
    schedule: "Mon, Wed, Fri - 4:00 PM - 6:00 PM",
    price: 1500,
    currency: "ETB",
    syllabus: [
      "Arabic alphabet and pronunciation",
      "Basic vocabulary and phrases",
      "Grammar fundamentals (Nahw)",
      "Morphology basics (Sarf)",
      "Reading comprehension",
      "Conversational Arabic",
    ],
    requirements: [
      "No prior Arabic knowledge required",
      "Dedication to homework",
    ],
    featured: true,
    enrollmentOpen: true,
    maxStudents: 100,
    startDate: "2026-02-15",
    endDate: "2027-02-14",
    masjidId: "1",
  },
  {
    id: "3",
    title: "Islamic Jurisprudence (Fiqh)",
    titleAr: "الفقه الإسلامي",
    description:
      "Study the fundamentals of Islamic jurisprudence covering worship, transactions, family law, and daily life matters according to the four major schools.",
    category: "Fiqh",
    level: "intermediate",
    duration: "18 months",
    students: 65,
    instructor: {
      id: "i3",
      name: "Sheikh Muhammad Ibrahim",
      title: "Senior Islamic Scholar",
    },
    schedule: "Tue, Thu - 6:00 PM - 8:00 PM",
    price: 2000,
    currency: "ETB",
    syllabus: [
      "Purification and Prayer",
      "Fasting and Zakat",
      "Hajj and Umrah",
      "Business transactions",
      "Marriage and family law",
      "Contemporary issues",
    ],
    requirements: [
      "Basic Islamic knowledge",
      "Completion of Arabic Level 1 or equivalent",
    ],
    featured: false,
    enrollmentOpen: true,
    maxStudents: 80,
    startDate: "2026-03-01",
    endDate: "2027-08-31",
    masjidId: "1",
  },
  {
    id: "4",
    title: "Hadith Sciences",
    titleAr: "علوم الحديث",
    description:
      "Deep dive into Hadith methodology, authentication criteria, chain of narration analysis, and study of major Hadith collections.",
    category: "Hadith",
    level: "advanced",
    duration: "2 years",
    students: 45,
    instructor: {
      id: "i4",
      name: "Dr. Yusuf Al-Azhari",
      title: "Hadith Studies Professor",
    },
    schedule: "Sat - 10:00 AM - 1:00 PM",
    price: 2500,
    currency: "ETB",
    syllabus: [
      "Introduction to Hadith sciences",
      "Classification of Hadith",
      "Chain of narration (Isnad) analysis",
      "Study of Sahih Bukhari",
      "Study of Sahih Muslim",
      "Comparative Hadith studies",
    ],
    requirements: [
      "Advanced Arabic proficiency",
      "Completion of Fiqh course",
      "Strong memorization skills",
    ],
    featured: false,
    enrollmentOpen: false,
    maxStudents: 50,
    startDate: "2026-09-01",
    endDate: "2028-08-31",
    masjidId: "1",
  },
  {
    id: "5",
    title: "Tafsir - Quranic Exegesis",
    titleAr: "تفسير القرآن الكريم",
    description:
      "Comprehensive study of Quranic interpretation covering historical context, linguistic analysis, and scholarly explanations of selected Surahs.",
    category: "Quran",
    level: "intermediate",
    duration: "1 year",
    students: 70,
    instructor: {
      id: "i1",
      name: "Sheikh Ahmad Al-Rashid",
      title: "Head of Quran Department",
    },
    schedule: "Sun, Wed - 5:00 PM - 7:00 PM",
    price: 1800,
    currency: "ETB",
    syllabus: [
      "Principles of Tafsir",
      "Historical Tafsir methodology",
      "Tafsir of Juz Amma",
      "Tafsir of selected Surahs",
      "Contemporary Tafsir discussions",
    ],
    requirements: ["Basic Arabic reading", "Familiarity with the Quran"],
    featured: true,
    enrollmentOpen: true,
    maxStudents: 90,
    startDate: "2026-02-01",
    endDate: "2027-01-31",
    masjidId: "1",
  },
  {
    id: "6",
    title: "Islamic History & Civilization",
    titleAr: "التاريخ الإسلامي والحضارة",
    description:
      "Explore the rich history of Islamic civilization from the Prophet's era through the golden age of Islam to contemporary times.",
    category: "History",
    level: "beginner",
    duration: "6 months",
    students: 55,
    instructor: {
      id: "i5",
      name: "Dr. Fatima Abdullah",
      title: "Islamic History Scholar",
    },
    schedule: "Fri - 2:00 PM - 5:00 PM",
    price: 1000,
    currency: "ETB",
    syllabus: [
      "Life of Prophet Muhammad (PBUH)",
      "The Rightly Guided Caliphs",
      "Umayyad and Abbasid dynasties",
      "Islamic golden age",
      "Muslim contributions to science",
      "Modern Islamic world",
    ],
    requirements: ["None - open to all"],
    featured: false,
    enrollmentOpen: true,
    maxStudents: 100,
    startDate: "2026-03-15",
    endDate: "2026-09-14",
    masjidId: "1",
  },
];

export const sampleLibraryItems = [
  {
    id: "1",
    title: "The Noble Quran - English Translation",
    author: "Dr. Muhammad Taqi-ud-Din Al-Hilali",
    category: "Quran",
    type: "pdf",
    description:
      "Complete English translation of the Holy Quran with Arabic text and commentary.",
    language: "English",
    publishedDate: "2020-01-01",
    views: 5420,
    downloads: 2100,
    featured: true,
    tags: ["Quran", "Translation", "English"],
    pages: 850,
  },
  {
    id: "2",
    title: "Sahih Al-Bukhari - Complete Collection",
    author: "Imam Al-Bukhari",
    category: "Hadith",
    type: "pdf",
    description:
      "The most authentic collection of Hadith compiled by Imam Al-Bukhari.",
    language: "Arabic/English",
    publishedDate: "2019-05-15",
    views: 3200,
    downloads: 1500,
    featured: true,
    tags: ["Hadith", "Sahih", "Bukhari"],
    pages: 1200,
  },
  {
    id: "3",
    title: "Learn Tajweed - Video Course",
    author: "Sheikh Ahmad Al-Rashid",
    category: "Quran",
    type: "video",
    description:
      "Complete video course covering all Tajweed rules for proper Quran recitation.",
    language: "English",
    publishedDate: "2025-08-20",
    views: 8500,
    downloads: 0,
    featured: true,
    tags: ["Tajweed", "Video", "Course"],
    duration: "12 hours",
    streamUrl: "#",
  },
  {
    id: "4",
    title: "Arabic Grammar Made Easy",
    author: "Ustadha Maryam Hassan",
    category: "Language",
    type: "pdf",
    description:
      "Simplified Arabic grammar guide for beginners learning classical Arabic.",
    language: "English",
    publishedDate: "2024-03-10",
    views: 2100,
    downloads: 980,
    featured: false,
    tags: ["Arabic", "Grammar", "Beginners"],
    pages: 250,
  },
  {
    id: "5",
    title: "Stories of the Prophets - Audio Series",
    author: "Imam Ibn Kathir",
    category: "History",
    type: "audio",
    description:
      "Narrated stories of the Prophets mentioned in the Quran, based on Ibn Kathir's work.",
    language: "English",
    publishedDate: "2025-01-05",
    views: 4300,
    downloads: 1800,
    featured: false,
    tags: ["Prophets", "Stories", "Audio"],
    duration: "8 hours",
  },
  {
    id: "6",
    title: "Fiqh of Worship",
    author: "Sheikh Muhammad Ibrahim",
    category: "Fiqh",
    type: "book",
    description:
      "Comprehensive guide to Islamic worship including prayer, fasting, and pilgrimage.",
    language: "English",
    publishedDate: "2023-11-20",
    views: 1500,
    downloads: 700,
    featured: false,
    tags: ["Fiqh", "Worship", "Prayer"],
    pages: 400,
  },
];

export const sampleEvents = [
  {
    id: "1",
    title: "Ramadan Preparation Workshop",
    description:
      "Join us for a comprehensive workshop on preparing spiritually and physically for the blessed month of Ramadan.",
    category: "Workshop",
    startDate: "2026-02-15T14:00:00",
    endDate: "2026-02-15T17:00:00",
    location: "Main Hall, Al-Noor Islamic Center",
    isOnline: false,
    registrationRequired: true,
    maxAttendees: 200,
    currentAttendees: 145,
    price: 0,
    currency: "ETB",
    masjidId: "1",
  },
  {
    id: "2",
    title: "Youth Islamic Leadership Summit",
    description:
      "A day-long summit empowering young Muslims with leadership skills rooted in Islamic values.",
    category: "Conference",
    startDate: "2026-02-22T09:00:00",
    endDate: "2026-02-22T18:00:00",
    location: "Conference Center",
    isOnline: true,
    registrationRequired: true,
    maxAttendees: 150,
    currentAttendees: 89,
    price: 100,
    currency: "ETB",
    masjidId: "1",
  },
  {
    id: "3",
    title: "Weekly Quran Circle",
    description:
      "Join our weekly gathering for Quran recitation, reflection, and discussion.",
    category: "Regular",
    startDate: "2026-02-07T19:00:00",
    endDate: "2026-02-07T21:00:00",
    location: "Musalla Room",
    isOnline: false,
    registrationRequired: false,
    maxAttendees: 50,
    currentAttendees: 35,
    price: 0,
    currency: "ETB",
    masjidId: "1",
  },
  {
    id: "4",
    title: "Sisters' Tafsir Class",
    description:
      "Weekly Tafsir class exclusively for sisters covering selected verses from the Quran.",
    category: "Class",
    startDate: "2026-02-08T10:00:00",
    endDate: "2026-02-08T12:00:00",
    location: "Sisters' Hall",
    isOnline: true,
    registrationRequired: true,
    maxAttendees: 80,
    currentAttendees: 62,
    price: 0,
    currency: "ETB",
    masjidId: "1",
  },
];

export const sampleBlogPosts = [
  {
    id: "1",
    title: "Preparing Your Heart for Ramadan",
    slug: "preparing-heart-ramadan",
    excerpt:
      "As the blessed month approaches, learn how to spiritually prepare yourself to maximize the benefits of Ramadan.",
    content: "",
    author: { id: "a1", name: "Sheikh Ahmad Al-Rashid" },
    category: "Spirituality",
    tags: ["Ramadan", "Spirituality", "Preparation"],
    publishedAt: "2026-01-28T10:00:00",
    updatedAt: "2026-01-28T10:00:00",
    featured: true,
    views: 1250,
  },
  {
    id: "2",
    title: "The Importance of Seeking Knowledge in Islam",
    slug: "importance-seeking-knowledge-islam",
    excerpt:
      "Explore the emphasis Islam places on education and the virtues of those who seek beneficial knowledge.",
    content: "",
    author: { id: "a2", name: "Dr. Fatima Abdullah" },
    category: "Education",
    tags: ["Knowledge", "Education", "Islam"],
    publishedAt: "2026-01-25T14:00:00",
    updatedAt: "2026-01-25T14:00:00",
    featured: false,
    views: 890,
  },
  {
    id: "3",
    title: "Building Strong Muslim Families",
    slug: "building-strong-muslim-families",
    excerpt:
      "Practical guidance on nurturing an Islamic household and raising righteous children in today's world.",
    content: "",
    author: { id: "a3", name: "Ustadha Maryam Hassan" },
    category: "Family",
    tags: ["Family", "Parenting", "Marriage"],
    publishedAt: "2026-01-22T09:00:00",
    updatedAt: "2026-01-22T09:00:00",
    featured: false,
    views: 720,
  },
];

export const sampleDonationCategories = [
  {
    id: "1",
    name: "Masjid Operations",
    description:
      "Support daily operations, utilities, and maintenance of the masjid.",
    goal: 500000,
    raised: 325000,
    currency: "ETB",
  },
  {
    id: "2",
    name: "Student Scholarships",
    description:
      "Help deserving students pursue Islamic education through financial aid.",
    goal: 200000,
    raised: 145000,
    currency: "ETB",
  },
  {
    id: "3",
    name: "Library Expansion",
    description: "Help us expand our digital and physical library resources.",
    goal: 150000,
    raised: 78000,
    currency: "ETB",
  },
  {
    id: "4",
    name: "Community Iftar",
    description: "Provide iftar meals during Ramadan for the community.",
    goal: 100000,
    raised: 42000,
    currency: "ETB",
  },
];
